---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: concourse-service-account
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kpack-concourse-resource-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kpack-concourse-resource
subjects:
  - kind: ServiceAccount
    name: concourse-service-account
    namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kpack-concourse-resource
rules:
  - apiGroups:
      - build.pivotal.io
    resources:
      - builds
      - images
    verbs:
      - get
      - list
      - create
      - update
      - delete
      - patch
      - watch